# Generated by Django 4.2.5 on 2023-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='msg',
            field=models.CharField(max_length=300),
        ),
    ]
