# Generated by Django 4.2.5 on 2023-10-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectTicketMapping',
        ),
    ]
